import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-text"
})

export const metadata: Metadata = {
  title: "yokai | quick crafti portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html className={`${inter.variable} h-full antialiased`}>
      <body>{children}</body>
    </html>
  );
}
